"""What every output format reports: the verdict, the summary and the SQL."""

import re
from dataclasses import dataclass
from enum import StrEnum

from dbdelta import __version__
from dbdelta.cli.analysis import Analysis
from dbdelta.diff import AddEnum, AddTable, AlterEnum, Change, DropEnum, DropTable
from dbdelta.risk import Finding, Level


class OutputFormat(StrEnum):
    TEXT = "text"
    SQL = "sql"
    JSON = "json"
    MARKDOWN = "markdown"


LEVELS = (Level.DANGER, Level.WARNING, Level.INFO)
"""Levels from the most to the least severe, the order reports list them in."""


@dataclass(frozen=True, slots=True)
class Verdict:
    """The outcome of ``dbdelta check``: dangerous changes fail it unless they are allowed."""

    dangers: tuple[Finding, ...]
    allow_destructive: bool

    @classmethod
    def of(cls, analysis: Analysis, *, allow_destructive: bool) -> "Verdict":
        dangers = tuple(finding for finding in analysis.findings if finding.level is Level.DANGER)
        return cls(dangers, allow_destructive)

    @property
    def passed(self) -> bool:
        return not self.dangers or self.allow_destructive

    def explain(self) -> str:
        count = _plural(len(self.dangers), "dangerous change")
        if not self.dangers:
            return "Check passed: no dangerous changes."
        if self.allow_destructive:
            return f"Check passed: {count} allowed by --allow-destructive."
        return (
            f"Check failed: {count}. Review them, then rerun with --allow-destructive "
            "to accept them."
        )


def summary(analysis: Analysis) -> str:
    """One sentence with the number of changes and of findings per level."""
    if not analysis.changes:
        return "No changes: the schemas are identical."
    changes = _plural(len(analysis.changes), "change")
    if not analysis.findings:
        return f"{changes}, no risks found."
    levels = ", ".join(
        f"{analysis.count(level)} {level}" for level in LEVELS if analysis.count(level)
    )
    return f"{changes}, {_plural(len(analysis.findings), 'risk')}: {levels}."


def loader_warnings(analysis: Analysis) -> list[str]:
    """What each loader skipped, prefixed with the source it comes from."""
    return [
        f"{side.location}: {warning}"
        for side in (analysis.source, analysis.target)
        for warning in side.warnings
    ]


def migration_sql(analysis: Analysis) -> str:
    """The migration script, headed by where it comes from and what to review in it."""
    lines = [
        f"Migration from {analysis.source.location} to {analysis.target.location} "
        f"({analysis.dialect}), generated by dbdelta {__version__}.",
        summary(analysis),
    ]
    if analysis.findings:
        lines.append("Read the comments marked DANGER, WARNING and INFO before running it.")
    lines += [f"Not compared: {warning}" for warning in loader_warnings(analysis)]
    return analysis.script.render(header="\n".join(lines))


def change_kind(change: Change) -> str:
    """A stable, machine-readable name for the kind of change, such as ``add_column``."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", type(change).__name__).lower()


def change_table(change: Change) -> str | None:
    """The table a change is about, or ``None`` for changes to enum types."""
    match change:
        case AddEnum() | DropEnum() | AlterEnum():
            return None
        case AddTable(table) | DropTable(table):
            return table.name
        case _:
            return change.table


def _plural(count: int, noun: str) -> str:
    return f"{count} {noun}" if count == 1 else f"{count} {noun}s"
