"""Compare two schemas and describe the difference as a list of typed changes."""

from dbdelta.diff.changes import (
    AddCheck,
    AddColumn,
    AddEnum,
    AddForeignKey,
    AddIndex,
    AddPrimaryKey,
    AddTable,
    AddUnique,
    AlterColumnType,
    AlterEnum,
    AlterIdentity,
    Change,
    ColumnChange,
    ConstraintChange,
    DropCheck,
    DropColumn,
    DropDefault,
    DropEnum,
    DropForeignKey,
    DropIndex,
    DropNotNull,
    DropPrimaryKey,
    DropTable,
    DropUnique,
    ReorderColumns,
    SetDefault,
    SetNotNull,
)
from dbdelta.diff.compare import diff_schemas
from dbdelta.diff.describe import describe

__all__ = [
    "AddCheck",
    "AddColumn",
    "AddEnum",
    "AddForeignKey",
    "AddIndex",
    "AddPrimaryKey",
    "AddTable",
    "AddUnique",
    "AlterColumnType",
    "AlterEnum",
    "AlterIdentity",
    "Change",
    "ColumnChange",
    "ConstraintChange",
    "DropCheck",
    "DropColumn",
    "DropDefault",
    "DropEnum",
    "DropForeignKey",
    "DropIndex",
    "DropNotNull",
    "DropPrimaryKey",
    "DropTable",
    "DropUnique",
    "ReorderColumns",
    "SetDefault",
    "SetNotNull",
    "describe",
    "diff_schemas",
]
