"""Compare two schemas and describe the difference as a list of typed changes."""

from dbdelta.diff.changes import (
    AddCheck,
    AddColumn,
    AddEnum,
    AddForeignKey,
    AddIndex,
    AddPrimaryKey,
    AddTable,
    AddUnique,
    AlterColumnType,
    AlterEnum,
    AlterIdentity,
    Change,
    ColumnChange,
    ConstraintChange,
    DropCheck,
    DropColumn,
    DropDefault,
    DropEnum,
    DropForeignKey,
    DropIndex,
    DropNotNull,
    DropPrimaryKey,
    DropTable,
    DropUnique,
    RenameChange,
    RenameColumn,
    RenameTable,
    ReorderColumns,
    SetDefault,
    SetNotNull,
)
from dbdelta.diff.compare import diff_schemas
from dbdelta.diff.describe import describe
from dbdelta.diff.renames import (
    RENAME_CONFIDENCE,
    PossibleRename,
    apply_renames,
    names_before_renames,
    possible_renames,
)

__all__ = [
    "RENAME_CONFIDENCE",
    "AddCheck",
    "AddColumn",
    "AddEnum",
    "AddForeignKey",
    "AddIndex",
    "AddPrimaryKey",
    "AddTable",
    "AddUnique",
    "AlterColumnType",
    "AlterEnum",
    "AlterIdentity",
    "Change",
    "ColumnChange",
    "ConstraintChange",
    "DropCheck",
    "DropColumn",
    "DropDefault",
    "DropEnum",
    "DropForeignKey",
    "DropIndex",
    "DropNotNull",
    "DropPrimaryKey",
    "DropTable",
    "DropUnique",
    "PossibleRename",
    "RenameChange",
    "RenameColumn",
    "RenameTable",
    "ReorderColumns",
    "SetDefault",
    "SetNotNull",
    "apply_renames",
    "describe",
    "diff_schemas",
    "names_before_renames",
    "possible_renames",
]
