-- Down migration from desired.sql back to current.sql (postgresql), generated by dbdelta 0.1.0.dev0.
-- 10 changes, 4 risks: 2 danger, 2 warning; 1 irreversible.
-- Read the comments marked DANGER, WARNING and INFO before running it.
-- Steps marked IRREVERSIBLE restore structure, not the data the up migration deleted.

BEGIN;

-- rename column orders.created_at to created
-- WARNING rename: Renaming column orders.created_at to created keeps its data, but application
--   code, views, functions and triggers that still use the old name fail. The database updates
--   keys, indexes and foreign keys itself.
ALTER TABLE "orders" RENAME COLUMN "created_at" TO "created";

-- drop foreign key order_items (product_id) -> products (id) ON DELETE RESTRICT
ALTER TABLE "order_items" DROP CONSTRAINT "order_items_product_id_fkey";

-- drop unique index ux_customers_email on customers (LOWER("email"))
DROP INDEX "ux_customers_email";

-- drop check constraint on order_items ("quantity" > 0)
ALTER TABLE "order_items" DROP CONSTRAINT "order_items_quantity_check";

-- drop index ix_orders_customer on orders (customer_id)
DROP INDEX "ix_orders_customer";

-- drop column customers.loyalty_tier
-- DANGER drop-column: Dropping customers.loyalty_tier permanently deletes its value in every
--   row.
ALTER TABLE "customers" DROP COLUMN "loyalty_tier";

-- recreate enum type order_status with values ('new', 'paid', 'shipped')
-- DANGER enum-values: Value 'refunded' is removed from order_status; rows that still hold them
--   make the conversion fail. PostgreSQL cannot remove or reorder enum values, so the type is
--   recreated and every column using it is converted, rewriting those tables under an ACCESS
--   EXCLUSIVE lock that blocks reads and writes.
ALTER TYPE "order_status" RENAME TO "order_status__dbdelta_old";

CREATE TYPE "order_status" AS ENUM ('new', 'paid', 'shipped');

ALTER TABLE "orders" ALTER COLUMN "status" DROP DEFAULT;

ALTER TABLE "orders" ALTER COLUMN "status" TYPE "order_status" USING "status"::text::"order_status";

ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'new';

DROP TYPE "order_status__dbdelta_old";

-- add column customers.phone text
-- IRREVERSIBLE: The up migration dropped customers.phone with its values; this adds it again
--   with every value NULL.
ALTER TABLE "customers" ADD COLUMN "phone" text;

-- change type of customers.email from varchar(120) to varchar(255)
ALTER TABLE "customers" ALTER COLUMN "email" TYPE varchar(255);

-- add foreign key order_items (product_id) -> products (id)
-- WARNING foreign-key: Adding the foreign key checks every row of order_items while holding
--   SHARE ROW EXCLUSIVE locks on order_items and products, which block writes to both; rows
--   without a match make the migration fail.
ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

COMMIT;
