-- Migration from current.sql to desired.sql (postgresql), generated by dbdelta 0.1.0.dev0.
-- 10 changes, 8 risks: 3 danger, 5 warning.
-- Read the comments marked DANGER, WARNING and INFO before running it.

-- New enum values are committed first: PostgreSQL cannot use an enum value in the
-- transaction that added it.
BEGIN;

-- change values of enum type order_status from ('new', 'paid', 'shipped') to ('new', 'paid', 'shipped', 'refunded')
ALTER TYPE "order_status" ADD VALUE 'refunded' AFTER 'shipped';

COMMIT;

BEGIN;

-- rename column orders.created to created_at
-- WARNING rename: Renaming column orders.created to created_at keeps its data, but application
--   code, views, functions and triggers that still use the old name fail. The database updates
--   keys, indexes and foreign keys itself.
ALTER TABLE "orders" RENAME COLUMN "created" TO "created_at";

-- drop foreign key order_items (product_id) -> products (id)
ALTER TABLE "order_items" DROP CONSTRAINT "order_items_product_id_fkey";

-- drop column customers.phone
-- DANGER drop-column: Dropping customers.phone permanently deletes its value in every row.
ALTER TABLE "customers" DROP COLUMN "phone";

-- add column customers.loyalty_tier text NOT NULL
-- DANGER add-not-null-column: customers.loyalty_tier is added as NOT NULL without a default,
--   which fails as soon as customers holds any row: existing rows would have no value.
ALTER TABLE "customers" ADD COLUMN "loyalty_tier" text NOT NULL;

-- change type of customers.email from varchar(255) to varchar(120)
-- DANGER narrowing-type: customers.email changes from varchar(255) to the narrower varchar(120).
--   Values longer than 120 characters make the migration fail.
-- WARNING type-rewrite: Changing customers.email from varchar(255) to varchar(120) makes
--   PostgreSQL rewrite the whole table and its indexes while holding an ACCESS EXCLUSIVE lock
--   that blocks reads and writes.
ALTER TABLE "customers" ALTER COLUMN "email" TYPE varchar(120);

-- add check constraint on order_items ("quantity" > 0)
-- WARNING check-violations: Rows already in order_items may violate CHECK ("quantity" > 0),
--   which makes the migration fail. PostgreSQL checks every row while holding an ACCESS
--   EXCLUSIVE lock that blocks reads and writes.
ALTER TABLE "order_items" ADD CHECK ("quantity" > 0);

-- add foreign key order_items (product_id) -> products (id) ON DELETE RESTRICT
-- WARNING foreign-key: Adding the foreign key checks every row of order_items while holding
--   SHARE ROW EXCLUSIVE locks on order_items and products, which block writes to both; rows
--   without a match make the migration fail.
ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE RESTRICT;

COMMIT;

-- CONCURRENTLY cannot run inside a transaction. If a statement fails, drop the INVALID
-- index it leaves behind before running it again.

-- create unique index ux_customers_email on customers (LOWER("email"))
-- WARNING unique-duplicates: Rows already in customers may contain duplicates of
--   (LOWER("email")), which make adding the unique index fail.
CREATE UNIQUE INDEX CONCURRENTLY "ux_customers_email" ON "customers" ((LOWER("email")));

-- create index ix_orders_customer on orders (customer_id)
CREATE INDEX CONCURRENTLY "ix_orders_customer" ON "orders" ("customer_id");
