from pathlib import Path

import pytest

from dbdelta.dialects import Dialect
from dbdelta.loaders import LoadError, load_ddl, load_ddl_file
from dbdelta.model import (
    CheckConstraint,
    Column,
    DataType,
    EnumType,
    Expression,
    ForeignKey,
    Identity,
    Index,
    IndexElement,
    PrimaryKey,
    ReferentialAction,
    Schema,
    Table,
    UniqueConstraint,
)

PG = Dialect.POSTGRESQL
SQLITE = Dialect.SQLITE

INTEGER = DataType("integer")
TEXT = DataType("text")


def load_table(sql: str, dialect: Dialect = PG, name: str = "t") -> Table:
    table = load_ddl(sql, dialect).schema.table(name)
    assert table is not None
    return table


def test_columns_keep_order_types_nullability_and_defaults() -> None:
    table = load_table(
        "CREATE TABLE t (id bigint NOT NULL, name varchar(50) NULL DEFAULT 'anon', score real)"
    )

    assert table.columns == (
        Column("id", DataType("bigint"), nullable=False),
        Column("name", DataType("varchar", (50,)), default="'anon'"),
        Column("score", DataType("real")),
    )


def test_serial_types_become_not_null_integers_with_serial_identity() -> None:
    table = load_table("CREATE TABLE t (a serial, b bigserial, c smallserial)")

    assert [(c.type.name, c.nullable, c.identity) for c in table.columns] == [
        ("integer", False, Identity.SERIAL),
        ("bigint", False, Identity.SERIAL),
        ("smallint", False, Identity.SERIAL),
    ]


def test_identity_columns_are_not_null() -> None:
    table = load_table(
        "CREATE TABLE t (a int GENERATED ALWAYS AS IDENTITY,"
        " b int GENERATED BY DEFAULT AS IDENTITY (START WITH 10))"
    )

    assert [(c.nullable, c.identity) for c in table.columns] == [
        (False, Identity.ALWAYS),
        (False, Identity.BY_DEFAULT),
    ]


def test_sqlite_autoincrement() -> None:
    table = load_table("CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT)", SQLITE)

    assert table.columns == (
        Column("id", INTEGER, nullable=False, identity=Identity.AUTOINCREMENT),
    )


def test_serial_is_just_a_type_name_in_sqlite() -> None:
    table = load_table("CREATE TABLE t (id serial)", SQLITE)

    assert table.columns == (Column("id", DataType("serial")),)


@pytest.mark.parametrize("dialect", list(Dialect))
def test_column_and_table_constraints_are_equivalent(dialect: Dialect) -> None:
    inline = load_table(
        "CREATE TABLE p (id int PRIMARY KEY);"
        "CREATE TABLE t (id int PRIMARY KEY, email text UNIQUE,"
        " age int CHECK (age > 0), p_id int REFERENCES p (id))",
        dialect,
    )
    table_level = load_table(
        "CREATE TABLE p (id int PRIMARY KEY);"
        "CREATE TABLE t (id int, email text, age int, p_id int, PRIMARY KEY (id),"
        " UNIQUE (email), CHECK (age > 0), FOREIGN KEY (p_id) REFERENCES p (id))",
        dialect,
    )

    assert inline == table_level
    assert inline.unique_constraints == (UniqueConstraint(("email",)),)
    assert inline.check_constraints == (CheckConstraint(Expression('"age" > 0')),)
    assert inline.foreign_keys == (ForeignKey(("p_id",), "p", ("id",)),)


def test_explicit_constraint_names_are_kept() -> None:
    table = load_table(
        "CREATE TABLE p (id int PRIMARY KEY);"
        "CREATE TABLE t (id int CONSTRAINT t_key PRIMARY KEY, a int CONSTRAINT a_pos CHECK (a > 0),"
        " CONSTRAINT uq UNIQUE (a), CONSTRAINT fk FOREIGN KEY (a) REFERENCES p (id))"
    )

    assert table.primary_key == PrimaryKey(("id",), "t_key")
    assert table.check_constraints[0].name == "a_pos"
    assert table.unique_constraints[0].name == "uq"
    assert table.foreign_keys[0].name == "fk"


@pytest.mark.parametrize("dialect", list(Dialect))
def test_primary_key_columns_are_not_null(dialect: Dialect) -> None:
    table = load_table("CREATE TABLE t (a text, b int, c int, PRIMARY KEY (a, b))", dialect)

    assert [column.nullable for column in table.columns] == [False, False, True]


def test_foreign_key_actions_and_implicit_referenced_columns() -> None:
    table = load_table(
        "CREATE TABLE p (id int PRIMARY KEY);"
        "CREATE TABLE t (a int REFERENCES p ON DELETE CASCADE ON UPDATE SET NULL,"
        " b int, FOREIGN KEY (b) REFERENCES p (id) ON DELETE RESTRICT ON UPDATE SET DEFAULT)"
    )

    assert table.foreign_keys == (
        ForeignKey(("a",), "p", ("id",), ReferentialAction.CASCADE, ReferentialAction.SET_NULL),
        ForeignKey(("b",), "p", ("id",), ReferentialAction.RESTRICT, ReferentialAction.SET_DEFAULT),
    )


def test_foreign_key_to_other_schema_keeps_qualified_name() -> None:
    table = load_table("CREATE TABLE t (a int REFERENCES audit.log (id))")

    assert table.foreign_keys[0].ref_table == "audit.log"


def test_foreign_key_without_columns_to_unknown_table_is_an_error() -> None:
    with pytest.raises(LoadError, match="without a column list"):
        load_ddl("CREATE TABLE t (a int REFERENCES missing)", PG)


def test_untracked_foreign_key_options_are_reported() -> None:
    result = load_ddl(
        "CREATE TABLE p (id int PRIMARY KEY);"
        "CREATE TABLE t (a int REFERENCES p (id) MATCH FULL DEFERRABLE INITIALLY IMMEDIATE)",
        PG,
    )

    assert result.warnings == (
        "foreign key ('a',) -> p: MATCH FULL is not tracked",
        "foreign key ('a',) -> p: DEFERRABLE is not tracked",
    )


def test_indexes() -> None:
    table = load_table(
        "CREATE TABLE t (a int, b text, c int);"
        "CREATE INDEX ix_plain ON t USING btree (a, c DESC);"
        "CREATE UNIQUE INDEX ix_partial ON t (b) WHERE c > 0;"
        "CREATE INDEX ix_expr ON t USING gin (lower(b), (a));"
        "CREATE INDEX ON t (c)"
    )

    assert table.indexes == (
        Index(None, (IndexElement("c"),)),
        Index(
            "ix_expr",
            (IndexElement(Expression('LOWER("b")')), IndexElement("a")),
            method="gin",
        ),
        Index("ix_partial", (IndexElement("b"),), unique=True, where=Expression('"c" > 0')),
        Index("ix_plain", (IndexElement("a"), IndexElement("c", descending=True))),
    )
    assert table.indexes[1].columns == {"a", "b"}
    assert table.indexes[2].columns == {"b", "c"}


def test_enum_types() -> None:
    schema = load_ddl(
        "CREATE TYPE public.mood AS ENUM ('sad', 'ok'); CREATE TABLE t (m mood DEFAULT 'ok')", PG
    ).schema

    assert schema.enums == (EnumType("mood", ("sad", "ok")),)
    assert schema.tables[0].columns == (Column("m", DataType("mood"), default="'ok'"),)


def test_alter_table_statements_are_applied() -> None:
    table = load_table(
        "CREATE TABLE p (id int PRIMARY KEY);"
        "CREATE TABLE t (a int, b int DEFAULT 1, c int NOT NULL);"
        "ALTER TABLE ONLY public.t ADD CONSTRAINT t_pkey PRIMARY KEY (a);"
        "ALTER TABLE t ADD CONSTRAINT t_b_fkey FOREIGN KEY (b) REFERENCES p (id) NOT VALID;"
        "ALTER TABLE t ADD COLUMN d text;"
        "ALTER TABLE t ALTER COLUMN b DROP DEFAULT;"
        "ALTER TABLE t ALTER COLUMN c DROP NOT NULL;"
        "ALTER TABLE t ALTER COLUMN d SET NOT NULL;"
        "ALTER TABLE t ALTER COLUMN d SET DEFAULT 'x'::text"
    )

    assert table.columns == (
        Column("a", INTEGER, nullable=False),
        Column("b", INTEGER),
        Column("c", INTEGER),
        Column("d", TEXT, nullable=False, default="'x'"),
    )
    assert table.primary_key == PrimaryKey(("a",), "t_pkey")
    assert table.foreign_keys == (ForeignKey(("b",), "p", ("id",), name="t_b_fkey"),)


def test_unsupported_alter_table_actions_are_skipped_with_a_warning() -> None:
    result = load_ddl(
        "CREATE TABLE t (a int, b int); ALTER TABLE t DROP COLUMN b;"
        " ALTER TABLE t ALTER COLUMN a TYPE bigint",
        PG,
    )

    assert len(result.warnings) == 2
    assert all(warning.startswith("skipped ALTER TABLE t") for warning in result.warnings)
    assert result.schema.tables[0].column_names == ("a", "b")


@pytest.mark.parametrize(
    ("statement", "message"),
    [
        ("ALTER TABLE missing ADD COLUMN a int", "unknown table 'missing'"),
        ("ALTER TABLE t ALTER COLUMN missing SET NOT NULL", "unknown column t.missing"),
        ("CREATE INDEX ix ON missing (a)", "unknown table 'missing'"),
        ("CREATE TABLE t (b int)", "table 't' is defined more than once"),
        ("CREATE TABLE u (a int, A int)", "declares column 'a' twice"),
        ("CREATE TABLE u (a int PRIMARY KEY, b int, PRIMARY KEY (b))", "more than one primary"),
        ("CREATE TABLE u (a int, PRIMARY KEY (nope))", "unknown column"),
        ("CREATE TYPE e AS ENUM ('x', 'x')", "more than once"),
        ("CREATE TYPE e AS ENUM ('x'); CREATE TYPE e AS ENUM ('y')", "defined more than once"),
    ],
)
def test_invalid_schemas_are_errors(statement: str, message: str) -> None:
    with pytest.raises(LoadError, match=message):
        load_ddl(f"CREATE TABLE t (a int); {statement}", PG)


def test_drop_statements_remove_objects() -> None:
    schema = load_ddl(
        "CREATE TYPE mood AS ENUM ('ok'); CREATE TABLE a (x int); CREATE TABLE b (x int);"
        "CREATE INDEX ix ON b (x); DROP TABLE IF EXISTS a, missing; DROP INDEX ix;"
        "DROP TYPE mood",
        PG,
    ).schema

    assert schema == Schema((Table("b", (Column("x", INTEGER),)),))


def test_if_not_exists_keeps_the_first_definition() -> None:
    schema = load_ddl(
        "CREATE TABLE t (a int); CREATE TABLE IF NOT EXISTS t (b int);"
        "CREATE INDEX ix ON t (a); CREATE INDEX IF NOT EXISTS ix ON t (a)",
        PG,
    ).schema

    assert schema.tables[0].column_names == ("a",)
    assert len(schema.tables[0].indexes) == 1


def test_postgres_folds_unquoted_identifiers() -> None:
    schema = load_ddl('CREATE TABLE Users (ID int, "Name" text, PRIMARY KEY (Id))', PG).schema

    assert schema.tables[0].name == "users"
    assert schema.tables[0].column_names == ("id", "Name")
    assert schema.tables[0].primary_key == PrimaryKey(("id",))


def test_sqlite_resolves_names_case_insensitively_to_their_declaration() -> None:
    schema = load_ddl(
        'CREATE TABLE "Orgs" (Id INTEGER PRIMARY KEY);'
        "CREATE TABLE Users (Org INT REFERENCES orgs (ID), Email TEXT, UNIQUE (email),"
        " CHECK (EMAIL <> ''));"
        "CREATE INDEX ix ON USERS (lower(EMAIL), ORG)",
        SQLITE,
    ).schema
    users = schema.table("Users")

    assert users is not None
    assert users.foreign_keys == (ForeignKey(("Org",), "Orgs", ("Id",)),)
    assert users.unique_constraints == (UniqueConstraint(("Email",)),)
    assert users.check_constraints[0].expression.columns == {"Email"}
    assert users.indexes[0].columns == {"Email", "Org"}


def test_objects_outside_the_default_schema_are_skipped() -> None:
    result = load_ddl("CREATE TABLE public.a (x int); CREATE TABLE audit.b (x int)", PG)

    assert [table.name for table in result.schema.tables] == ["a"]
    assert result.warnings == (
        "skipped CREATE TABLE audit.b (x INT): only objects in schema 'public' are loaded",
    )


def test_statements_that_do_not_change_the_schema_are_ignored_silently() -> None:
    result = load_ddl(
        """
        SET statement_timeout = 0;
        SELECT pg_catalog.set_config('search_path', '', false);
        BEGIN;
        CREATE TABLE t (a int);
        INSERT INTO t VALUES (1);
        COMMENT ON TABLE t IS 'demo';
        ALTER TABLE public.t OWNER TO app;
        GRANT SELECT ON t TO reader;
        COMMIT;
        """,
        PG,
    )

    assert result.warnings == ()


@pytest.mark.parametrize(
    ("statement", "reason"),
    [
        ("CREATE VIEW v AS SELECT 1", "CREATE VIEW is not supported"),
        ("CREATE SEQUENCE s", "sequences are not supported"),
        ("CREATE EXTENSION citext", "this statement is not supported"),
        ("CREATE TYPE pair AS (a int, b int)", "CREATE TYPE is not supported"),
        ("CREATE TEMP TABLE tmp (a int)", "temporary tables are not part of the schema"),
        ("CREATE TABLE copy AS SELECT 1 AS a", "tables created from a query are not supported"),
        ("DROP VIEW v", "DROP VIEW is not supported"),
        ("TRUNCATE t", "this statement is not supported"),
    ],
)
def test_unsupported_objects_are_skipped_with_a_warning(statement: str, reason: str) -> None:
    result = load_ddl(f"CREATE TABLE t (a int); {statement}", PG)

    assert [table.name for table in result.schema.tables] == ["t"]
    assert len(result.warnings) == 1
    assert result.warnings[0].startswith("skipped ")
    assert result.warnings[0].endswith(reason)


def test_untracked_column_and_table_options_are_reported() -> None:
    result = load_ddl(
        "CREATE TABLE t (a TEXT COLLATE NOCASE, b INT GENERATED ALWAYS AS (1) STORED,"
        " PRIMARY KEY (a)) WITHOUT ROWID;"
        "CREATE TABLE s (a INT) STRICT",
        SQLITE,
    )

    assert result.warnings == (
        "column t.a: COLLATE NOCASE is not tracked",
        "column t.b: generated column is treated as a regular one",
        "table 't': WITHOUT ROWID is not tracked",
        "table 's': STRICT is not tracked",
    )


def test_sqlite_columns_may_be_declared_without_a_type() -> None:
    table = load_table("CREATE TABLE t (a, b INT)", SQLITE)

    assert table.columns == (Column("a", DataType("")), Column("b", INTEGER))


def test_parse_errors_report_their_position() -> None:
    with pytest.raises(LoadError, match=r"line 2, column \d+: .* near 'KEY'"):
        load_ddl("CREATE TABLE t (a int,\n b int PRIMARY KEY KEY);", PG)


def test_load_ddl_file(tmp_path: Path) -> None:
    path = tmp_path / "schema.sql"
    path.write_text("CREATE TABLE t (a int);", encoding="utf-8")

    assert load_ddl_file(path, PG).schema == Schema((Table("t", (Column("a", INTEGER),)),))


def test_load_ddl_file_errors_name_the_file(tmp_path: Path) -> None:
    path = tmp_path / "broken.sql"
    path.write_text("CREATE TABLE t (a int PRIMARY KEY KEY);", encoding="utf-8")

    with pytest.raises(LoadError, match=r"broken\.sql: line 1"):
        load_ddl_file(path, PG)
    with pytest.raises(LoadError, match=r"cannot read .*missing\.sql"):
        load_ddl_file(tmp_path / "missing.sql", PG)


def test_exclusion_constraints_are_reported() -> None:
    result = load_ddl("CREATE TABLE t (a int, EXCLUDE USING gist (a WITH =))", PG)

    assert result.warnings == ("table 't': EXCLUDE USING gist(a WITH =) is not tracked",)


@pytest.mark.parametrize(
    "statement",
    [
        "CREATE INDEX ix ON audit.t (a)",
        "CREATE TYPE audit.mood AS ENUM ('ok')",
        "ALTER TABLE audit.t ADD COLUMN b int",
        "DROP TABLE audit.t",
    ],
)
def test_statements_on_other_schemas_are_skipped(statement: str) -> None:
    result = load_ddl(f"CREATE TABLE t (a int); {statement}", PG)

    assert result.schema == load_ddl("CREATE TABLE t (a int)", PG).schema
    assert result.warnings[0].endswith("only objects in schema 'public' are loaded")


def test_empty_statements_are_ignored() -> None:
    assert load_ddl(";; CREATE TABLE t (a int);;", PG).schema.tables[0].name == "t"


def test_long_statements_are_shortened_in_warnings() -> None:
    columns = ", ".join(f"column_{number} int" for number in range(20))
    result = load_ddl(f"CREATE TEMP TABLE t ({columns})", PG)

    snippet = result.warnings[0].removeprefix("skipped ").split(":")[0]
    assert len(snippet) == 70
    assert snippet.endswith("...")


def test_unknown_sqlite_table_option_is_a_parse_error() -> None:
    with pytest.raises(LoadError, match="Expected ROWID after WITHOUT"):
        load_ddl("CREATE TABLE t (a) WITHOUT OIDS", SQLITE)
