BEGIN;

-- create table d
CREATE TABLE "d" (
    "id" bigserial NOT NULL,
    PRIMARY KEY ("id")
);

-- change identity of a.id from serial to by default
ALTER TABLE "a" ALTER COLUMN "id" DROP DEFAULT;

ALTER TABLE "a" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('"a"', 'id'), COALESCE(MAX("id"), 0) + 1, false) FROM "a";

-- change identity of b.id from none to always
ALTER TABLE "b" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY;

SELECT setval(pg_get_serial_sequence('"b"', 'id'), COALESCE(MAX("id"), 0) + 1, false) FROM "b";

-- change identity of c.id from always to none
ALTER TABLE "c" ALTER COLUMN "id" DROP IDENTITY;

COMMIT;
