"""The dbdelta commands end to end: sources on disk, options, config, output and exit codes."""

import json
import logging
import os
import shutil
import sqlite3
from contextlib import closing
from pathlib import Path

import psycopg
import pytest
from tests.conftest import Snapshot
from tests.support.databases import POSTGRES_URL_VARIABLE
from tests.support.fixtures import FIXTURES
from typer.testing import CliRunner, Result

from dbdelta import __version__
from dbdelta.cli.app import EXIT_CHECK_FAILED, EXIT_USAGE, app
from dbdelta.dialects import Dialect

MIXED = FIXTURES / "common" / "19_mixed_changes"
CREATE = FIXTURES / "common" / "01_create_table"
SNAPSHOTS = FIXTURES / "cli"


@pytest.fixture(autouse=True)
def workspace(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    """Run in a directory holding the mixed pair, with output independent of the terminal.

    Relative paths keep the snapshots the same on every machine.
    """
    for variable in ("FORCE_COLOR", "NO_COLOR", "TTY_COMPATIBLE", "TTY_INTERACTIVE"):
        monkeypatch.delenv(variable, raising=False)
    monkeypatch.setenv("COLUMNS", "100")
    for name in ("a.sql", "b.sql"):
        shutil.copy(MIXED / name, tmp_path / name)
    monkeypatch.chdir(tmp_path)


def run(*args: str | Path) -> Result:
    return CliRunner().invoke(app, [str(arg) for arg in args])


def mixed(command: str, *options: str | Path) -> Result:
    return run(command, "a.sql", "b.sql", *options)


def without_version(text: str) -> str:
    return text.replace(__version__, "<version>")


def test_diff_reports_changes_and_risks(snapshot: Snapshot) -> None:
    result = mixed("diff")

    assert result.exit_code == 0
    assert result.stderr == ""
    snapshot(SNAPSHOTS / "diff.txt", without_version(result.stdout))


def test_plan_prints_the_migration_with_a_header() -> None:
    result = mixed("plan")

    assert result.exit_code == 0
    header, _, script = result.stdout.partition("\n\n")
    assert header.startswith("-- Migration from a.sql to b.sql (postgresql), generated by")
    assert script == (MIXED / "expected.postgresql.sql").read_text(encoding="utf-8")


def test_plan_for_sqlite() -> None:
    result = mixed("plan", "--dialect", "sqlite")

    assert result.exit_code == 0
    assert result.stdout.endswith((MIXED / "expected.sqlite.sql").read_text(encoding="utf-8"))


def test_check_fails_on_dangerous_changes() -> None:
    result = mixed("check")

    assert result.exit_code == EXIT_CHECK_FAILED
    assert result.stdout.rstrip().endswith(
        "Check failed: 2 dangerous changes. Review them, then rerun with --allow-destructive "
        "to accept them."
    )


def test_check_passes_when_destruction_is_allowed() -> None:
    result = mixed("check", "--allow-destructive")

    assert result.exit_code == 0
    assert "Check passed: 2 dangerous changes allowed by --allow-destructive." in result.stdout


def test_check_passes_without_dangerous_changes() -> None:
    result = run("check", CREATE / "a.sql", CREATE / "b.sql")

    assert result.exit_code == 0
    assert "Check passed: no dangerous changes." in result.stdout


def test_check_reports_its_verdict_on_stderr_for_machine_formats() -> None:
    result = mixed("check", "--format", "json")

    assert result.exit_code == EXIT_CHECK_FAILED
    assert json.loads(result.stdout)["check"] == {
        "passed": False,
        "allow_destructive": False,
        "dangers": 2,
    }
    assert result.stderr.startswith("Check failed: 2 dangerous changes.")


def test_markdown_report(snapshot: Snapshot) -> None:
    result = mixed("check", "--format", "markdown")

    snapshot(SNAPSHOTS / "check.md", without_version(result.stdout))


def test_json_report(snapshot: Snapshot) -> None:
    result = mixed("diff", "--format", "json")
    report = json.loads(result.stdout)

    assert report["summary"] == {"changes": 16, "danger": 2, "warning": 6, "info": 0}
    for finding in report["findings"]:
        assert all(report["changes"][index]["risk"] for index in finding["changes"])
    snapshot(SNAPSHOTS / "diff.json", without_version(result.stdout))


def test_identical_schemas() -> None:
    same = "b.sql"

    assert "No changes: the schemas are identical." in run("diff", same, same).stdout
    assert run("plan", same, same).stdout.endswith("-- No changes: the schemas are identical.\n")


def test_output_goes_to_a_file_and_status_to_stderr(tmp_path: Path) -> None:
    output = tmp_path / "migration.sql"

    result = mixed("plan", "--output", output)

    assert result.exit_code == 0
    assert result.stdout == ""
    assert result.stderr == (
        f"Wrote the migration to {output}. 16 changes, 8 risks: 2 danger, 6 warning.\n"
    )
    assert output.read_text(encoding="utf-8").endswith("COMMIT;\n")


def test_text_written_to_a_file_has_no_colors_even_when_forced(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("FORCE_COLOR", "1")
    output = tmp_path / "report.txt"

    mixed("diff", "--output", output)

    text = output.read_text(encoding="utf-8")
    assert "\x1b[" not in text
    assert not any(line.endswith(" ") for line in text.splitlines())


def test_output_is_plain_when_stdout_is_not_a_terminal() -> None:
    assert "\x1b[" not in mixed("diff").stdout


def test_force_color_colors_the_report(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("FORCE_COLOR", "1")

    assert "\x1b[" in mixed("diff").stdout


def test_an_unwritable_output_is_an_error(tmp_path: Path) -> None:
    result = mixed("plan", "--output", tmp_path / "missing" / "migration.sql")

    assert result.exit_code == EXIT_USAGE
    assert result.stderr.startswith("error: cannot write")


def test_names_are_never_read_as_rich_markup(tmp_path: Path) -> None:
    source = tmp_path / "a.sql"
    target = tmp_path / "b.sql"
    source.write_text("", encoding="utf-8")
    target.write_text('CREATE TABLE "[bold]x[/bold]" (id int);', encoding="utf-8")

    result = run("diff", source, target)

    assert "create table [bold]x[/bold]" in result.stdout


def test_ignored_tables_and_rules_are_left_out() -> None:
    result = mixed(
        "check",
        "--ignore-table",
        "legacy_*",
        "--ignore-rule",
        "drop-column",
        "--format",
        "json",
    )
    report = json.loads(result.stdout)

    assert result.exit_code == 0
    assert "drop table legacy_scores" not in [change["description"] for change in report["changes"]]
    assert {finding["rule"] for finding in report["findings"]} == {
        "check-violations",
        "foreign-key",
        "index-lock",
        "set-not-null",
        "type-rewrite",
    }


def test_an_unknown_rule_is_a_usage_error() -> None:
    result = mixed("diff", "--ignore-rule", "drop-colum")

    assert result.exit_code == EXIT_USAGE
    assert result.stderr.startswith("error: unknown risk rule(s): drop-colum; the rules are: ")


def test_settings_come_from_dbdelta_toml(tmp_path: Path) -> None:
    (tmp_path / "dbdelta.toml").write_text(
        'dialect = "sqlite"\nallow-destructive = true\n', encoding="utf-8"
    )

    result = mixed("check", "--format", "sql")

    assert result.exit_code == 0
    assert "PRAGMA foreign_keys = OFF;" in result.stdout


def test_options_override_dbdelta_toml(tmp_path: Path) -> None:
    (tmp_path / "dbdelta.toml").write_text("allow-destructive = true\n", encoding="utf-8")

    assert mixed("check").exit_code == 0
    assert mixed("check", "--no-allow-destructive").exit_code == EXIT_CHECK_FAILED


def test_an_explicit_config_file_is_used(tmp_path: Path) -> None:
    config = tmp_path / "ci.toml"
    config.write_text('ignore-tables = ["legacy_*"]\n', encoding="utf-8")

    result = mixed("diff", "--config", config, "--format", "json")

    assert json.loads(result.stdout)["summary"]["changes"] == 15


def test_an_invalid_config_is_a_usage_error(tmp_path: Path) -> None:
    (tmp_path / "dbdelta.toml").write_text("concurrent_indexes = true\n", encoding="utf-8")

    result = mixed("diff")

    assert result.exit_code == EXIT_USAGE
    assert result.stderr == (
        f"error: {tmp_path / 'dbdelta.toml'}: unknown setting 'concurrent_indexes'; "
        "did you mean 'concurrent-indexes'?\n"
    )


def test_concurrent_indexes_move_index_builds_out_of_the_transaction() -> None:
    result = mixed("plan", "--concurrent-indexes")

    assert 'CREATE UNIQUE INDEX CONCURRENTLY "ux_players_email"' in result.stdout


def test_strict_column_order_reports_reordered_columns(tmp_path: Path) -> None:
    source = tmp_path / "a.sql"
    target = tmp_path / "b.sql"
    source.write_text("CREATE TABLE t (a int, b int);", encoding="utf-8")
    target.write_text("CREATE TABLE t (b int, a int);", encoding="utf-8")

    assert "No changes" in run("diff", source, target).stdout
    assert "No changes" not in run("diff", source, target, "--strict-column-order").stdout


def test_a_file_that_does_not_parse_is_an_error_without_a_traceback(tmp_path: Path) -> None:
    broken = tmp_path / "broken.sql"
    broken.write_text("CREATE TABLE (;", encoding="utf-8")

    result = run("diff", broken, "b.sql")

    assert result.exit_code == EXIT_USAGE
    assert result.stderr.startswith(f"error: {broken}: ")
    assert "Traceback" not in result.output


def test_a_missing_file_is_an_error(tmp_path: Path) -> None:
    result = run("plan", tmp_path / "missing.sql", "b.sql")

    assert result.exit_code == EXIT_USAGE
    assert "cannot read" in result.stderr


def test_databases_of_different_dialects_are_an_error() -> None:
    result = run("diff", "postgresql://db/app", "sqlite:///app.db")

    assert result.exit_code == EXIT_USAGE
    assert "both sides must use one dialect" in result.stderr


def test_a_live_sqlite_database_can_be_either_side(tmp_path: Path) -> None:
    database = tmp_path / "app.db"
    with closing(sqlite3.connect(database)) as connection:
        connection.executescript((MIXED / "a.sql").read_text(encoding="utf-8"))
        connection.execute("CREATE VIEW names AS SELECT name FROM players")

    result = run("plan", f"sqlite:///{database}", "b.sql")

    assert result.exit_code == 0
    assert result.stdout.endswith((MIXED / "expected.sqlite.sql").read_text(encoding="utf-8"))
    assert result.stderr == (
        f"warning: sqlite:///{database}: skipped view 'names': it is not supported\n"
    )


@pytest.mark.parametrize("output_format", ["text", "markdown"])
def test_reports_list_what_was_not_compared(tmp_path: Path, output_format: str) -> None:
    source = tmp_path / "views.sql"
    source.write_text("CREATE VIEW v AS SELECT 1;", encoding="utf-8")

    result = run("diff", source, "b.sql", "--format", output_format)

    assert "CREATE VIEW is not supported" in result.stdout
    # Only formats that are not the text report repeat warnings on stderr.
    assert (result.stderr == "") is (output_format == "text")


def test_sqlglot_does_not_log_statements_dbdelta_reports_itself() -> None:
    run("--version")
    mixed("diff")

    assert logging.getLogger("sqlglot").getEffectiveLevel() == logging.ERROR


@pytest.mark.postgres
def test_a_live_postgresql_database_is_compared(postgres: psycopg.Connection) -> None:
    postgres.execute((MIXED / "a.sql").read_text(encoding="utf-8"))
    row = postgres.execute("SELECT current_schema()").fetchone()
    assert row is not None

    result = run("plan", os.environ[POSTGRES_URL_VARIABLE], "b.sql", "--schema", row[0])

    # The database knows the names it gave constraints, so only the comments differ.
    assert result.exit_code == 0, result.output
    expected = (MIXED / f"expected.{Dialect.POSTGRESQL}.sql").read_text(encoding="utf-8")
    assert _statements(result.stdout) == _statements(expected)


def _statements(sql: str) -> list[str]:
    return [line for line in sql.splitlines() if line and not line.startswith("--")]
