"""The live PostgreSQL loader: what it reads beyond the DDL equivalence cases."""

import os

import psycopg
import pytest
from sqlalchemy import Connection, text
from tests.support.databases import POSTGRES_URL_VARIABLE, load_postgres_connection

from dbdelta.dialects import Dialect
from dbdelta.loaders import LoadError, LoadResult, database, load_database, load_source
from dbdelta.model import Identity

pytestmark = pytest.mark.postgres


def _schema(connection: psycopg.Connection) -> str:
    row = connection.execute("SELECT current_schema()").fetchone()
    assert row is not None
    return str(row[0])


def test_views_and_other_relations_are_skipped_with_a_warning(
    postgres: psycopg.Connection,
) -> None:
    postgres.execute("CREATE TABLE t (a int)")
    postgres.execute("CREATE VIEW v AS SELECT a FROM t")
    postgres.execute("CREATE MATERIALIZED VIEW mv AS SELECT a FROM t")

    result = load_postgres_connection(postgres)

    assert [table.name for table in result.schema.tables] == ["t"]
    assert result.warnings == (
        "skipped materialized view 'mv': it is not supported",
        "skipped view 'v': it is not supported",
    )


def test_partitions_are_neither_tables_nor_warnings(postgres: psycopg.Connection) -> None:
    postgres.execute("CREATE TABLE t (a int)")
    postgres.execute("CREATE TABLE p (a int) PARTITION BY RANGE (a)")
    postgres.execute("CREATE TABLE p1 PARTITION OF p FOR VALUES FROM (0) TO (10)")

    result = load_postgres_connection(postgres)

    assert [table.name for table in result.schema.tables] == ["t"]
    assert result.warnings == ("skipped partitioned table 'p': it is not supported",)


def test_row_estimates_come_from_the_statistics(postgres: psycopg.Connection) -> None:
    postgres.execute("CREATE TABLE analyzed (a int)")
    postgres.execute("CREATE TABLE fresh (a int)")
    postgres.execute("INSERT INTO analyzed SELECT generate_series(1, 500)")
    postgres.execute("ANALYZE analyzed")

    result = load_postgres_connection(postgres)

    # A table that was never analyzed has no estimate rather than a wrong one.
    assert result.row_estimates == {"analyzed": 500}


def test_serial_needs_a_sequence_the_column_owns(postgres: psycopg.Connection) -> None:
    postgres.execute("CREATE SEQUENCE shared")
    postgres.execute(
        "CREATE TABLE t (owned serial, borrowed int DEFAULT nextval('shared'), "
        "generated int GENERATED BY DEFAULT AS IDENTITY)"
    )

    table = load_postgres_connection(postgres).schema.table("t")

    assert table is not None
    assert [(column.identity, column.default) for column in table.columns] == [
        (Identity.SERIAL, None),
        (None, "NEXTVAL('shared')"),
        (Identity.BY_DEFAULT, None),
    ]


def test_deferrable_foreign_keys_are_reported(postgres: psycopg.Connection) -> None:
    postgres.execute("CREATE TABLE p (id int PRIMARY KEY)")
    postgres.execute(
        "CREATE TABLE c (p int CONSTRAINT c_p REFERENCES p DEFERRABLE INITIALLY DEFERRED)"
    )

    result = load_postgres_connection(postgres)

    assert result.warnings == ("foreign key 'c_p' of 'c': DEFERRABLE and MATCH are not tracked",)


def test_only_the_requested_schema_is_loaded(postgres: psycopg.Connection) -> None:
    postgres.execute("CREATE TABLE here (a int)")
    postgres.execute("CREATE SCHEMA IF NOT EXISTS dbdelta_elsewhere")
    try:
        postgres.execute("CREATE TABLE dbdelta_elsewhere.there (a int)")
        url = os.environ[POSTGRES_URL_VARIABLE]

        here = load_source(url, Dialect.POSTGRESQL, _schema(postgres))
        there = load_database(url, "dbdelta_elsewhere")
    finally:
        postgres.execute("DROP SCHEMA dbdelta_elsewhere CASCADE")

    assert [table.name for table in here.schema.tables] == ["here"]
    assert [table.name for table in there.schema.tables] == ["there"]


def test_a_missing_schema_is_an_error(postgres: psycopg.Connection) -> None:  # noqa: ARG001
    with pytest.raises(LoadError, match="schema 'no_such_schema' does not exist"):
        load_database(os.environ[POSTGRES_URL_VARIABLE], "no_such_schema")


def test_the_connection_is_read_only(
    postgres: psycopg.Connection,  # noqa: ARG001
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def write_instead(connection: Connection, schema: str) -> LoadResult:
        connection.execute(text(f'CREATE TABLE "{schema}".sneaky (a int)'))
        raise AssertionError("the write succeeded")

    monkeypatch.setattr(database, "load_postgresql", write_instead)

    with pytest.raises(LoadError, match="read-only transaction"):
        load_database(os.environ[POSTGRES_URL_VARIABLE], "public")


def test_an_unreachable_server_is_a_load_error_without_the_password() -> None:
    with pytest.raises(LoadError) as error:
        load_database("postgresql://user:secret@127.0.0.1:1/db")

    assert "secret" not in str(error.value)
    assert "***" in str(error.value)
