"""Generated keys keep working after a column changes how it generates them.

A schema round-trip cannot show this: the next INSERT must get a fresh key, which depends
on which sequence the migration continued and on what it left behind.
"""

import psycopg
import pytest
from tests.support.databases import load_postgres_connection, run_postgres_script

from dbdelta.cli.analysis import migrate
from dbdelta.cli.config import Settings
from dbdelta.dialects import Dialect
from dbdelta.loaders import load_ddl

pytestmark = pytest.mark.postgres

PG = Dialect.POSTGRESQL
KINDS = {
    "serial": "serial",
    "identity": "integer GENERATED BY DEFAULT AS IDENTITY",
    "always": "integer GENERATED ALWAYS AS IDENTITY",
}
TRANSITIONS = [(old, new) for old in KINDS for new in KINDS if old != new]


@pytest.mark.parametrize(("old", "new"), TRANSITIONS, ids=[f"{o}->{n}" for o, n in TRANSITIONS])
def test_inserts_continue_after_the_existing_keys(
    postgres: psycopg.Connection, old: str, new: str
) -> None:
    postgres.execute(f"CREATE TABLE t (id {KINDS[old]} PRIMARY KEY, x int)")
    postgres.execute("INSERT INTO t (x) SELECT generate_series(1, 3)")
    source = load_postgres_connection(postgres).schema
    target = load_ddl(f"CREATE TABLE t (id {KINDS[new]} PRIMARY KEY, x int)", PG).schema

    run_postgres_script(postgres, migrate(source, target, PG, Settings()).script)
    row = postgres.execute("INSERT INTO t (x) VALUES (4) RETURNING id").fetchone()
    sequences = postgres.execute(
        "SELECT count(*) FROM pg_class WHERE relkind = 'S'"
        " AND relnamespace = current_schema()::regnamespace"
    ).fetchone()

    assert row == (4,)
    assert sequences == (1,)
