"""The examples in ``examples/`` work, and the output they show is what dbdelta prints.

README quotes these outputs, so they are compared like snapshots: rerun with
``--update-snapshots`` after changing what dbdelta prints.
"""

import re
import tomllib
from dataclasses import fields

import psycopg
import pytest
from tests.support.databases import load_postgres_connection, run_postgres_script
from tests.support.fixtures import FIXTURES
from typer.testing import CliRunner

from dbdelta.cli.analysis import migrate
from dbdelta.cli.app import app
from dbdelta.cli.config import Settings, read_config
from dbdelta.dialects import Dialect
from dbdelta.diff import diff_schemas
from dbdelta.loaders import load_ddl

SHOP = FIXTURES.parent.parent / "examples" / "shop"
OUTPUTS = [
    ("diff.txt", ["diff"]),
    ("migration.sql", ["plan", "--detect-renames", "--concurrent-indexes"]),
    ("down.sql", ["plan", "--detect-renames", "--down"]),
    ("check.md", ["check", "--detect-renames", "--format", "markdown"]),
]
PG = Dialect.POSTGRESQL
_VERSION = re.compile(r"generated by dbdelta \S+?\.(?=\s)")


@pytest.fixture(autouse=True)
def in_the_example(monkeypatch: pytest.MonkeyPatch) -> None:
    for variable in ("FORCE_COLOR", "NO_COLOR", "TTY_COMPATIBLE", "TTY_INTERACTIVE"):
        monkeypatch.delenv(variable, raising=False)
    monkeypatch.setenv("COLUMNS", "100")
    monkeypatch.chdir(SHOP)


@pytest.mark.parametrize(("name", "command"), OUTPUTS, ids=[name for name, _ in OUTPUTS])
def test_shown_output_is_current(
    name: str, command: list[str], request: pytest.FixtureRequest
) -> None:
    result = CliRunner().invoke(app, [command[0], "current.sql", "desired.sql", *command[1:]])
    stored = SHOP / "output" / name

    if request.config.getoption("--update-snapshots"):
        stored.write_text(result.stdout, encoding="utf-8")
    assert _unversioned(result.stdout) == _unversioned(stored.read_text(encoding="utf-8"))


@pytest.mark.postgres
def test_the_migrations_run_both_ways(postgres: psycopg.Connection) -> None:
    postgres.execute((SHOP / "current.sql").read_text(encoding="utf-8"))
    current = load_postgres_connection(postgres).schema
    desired = load_ddl((SHOP / "desired.sql").read_text(encoding="utf-8"), PG).schema
    settings = Settings(detect_renames=True, concurrent_indexes=True)

    run_postgres_script(postgres, migrate(current, desired, PG, settings).script)
    reached = load_postgres_connection(postgres).schema
    run_postgres_script(postgres, migrate(reached, current, PG, settings, down=True).script)

    assert diff_schemas(reached, desired, PG) == ()
    assert diff_schemas(load_postgres_connection(postgres).schema, current, PG) == ()


def _unversioned(text: str) -> str:
    return _VERSION.sub("generated by dbdelta <version>.", text)


def test_the_example_configuration_shows_every_setting() -> None:
    path = SHOP.parent / "dbdelta.toml"

    with path.open("rb") as file:
        keys = set(tomllib.load(file))

    assert keys == {field.name.replace("_", "-") for field in fields(Settings)}
    read_config(path)
